run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows declaration at'
    - linters:
        - errorlint
      # Disable the check to test errors type assertion on switches.
      text: type switch on error will fail on wrapped errors. Use errors.As to check for specific errors
    # Exclude the following linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
    - path: main.go
      linters:
        - gocyclo

linters:
  disable-all: true
  enable:
    - errcheck
    - ginkgolinter
    - prealloc
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  revive:
    rules:
      - name: comment-spacings

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

  goheader:
    values:
      const:
        AUTHORS: The Falco Authors
    template: |-
      Copyright (C) {{ YEAR }} {{ AUTHORS }}

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
      
      SPDX-License-Identifier: Apache-2.0

  lll:
    line-length: 150

  gci:
    sections:
      - standard                          # Captures all standard packages if they do not match another section.
      - default                           # Contains all imports that could not be matched to another section type.
      - prefix(github.com/alacuku/falco-operator)  # Groups all imports with the specified Prefix.
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: github.com/alacuku/falco-operator
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  dupl:
    threshold: 300
