# Image URL to use all building/pushing image targets
IMG ?= falcosecurity/falco-operator:latest
RELEASE ?= v0.2.1
COMMIT ?= $(shell git rev-parse HEAD)
BUILD_DATE ?= $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
OPERATOR ?= instance
PROJECT ?= github.com/falcosecurity/falco-operator
ARTIFACT_OPERATOR_IMAGE ?= docker.io/falcosecurity/artifact-operator:latest

# SED_INPLACE defines the sed in-place flag based on the OS.
# macOS requires an empty string argument after -i, while Linux does not.
ifeq ($(shell uname -s),Darwin)
SED_INPLACE := sed -i ''
else
SED_INPLACE := sed -i
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

.PHONY: all
all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: manifests
manifests: ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	go tool controller-gen rbac:roleName=falco-operator-role crd:generateEmbeddedObjectMeta=true paths="./..." output:crd:artifacts:config=chart/falco-operator/crds output:rbac:stdout | sed -n '/^rules:/,$$p' > chart/falco-operator/files/ClusterRole.yaml

.PHONY: generate
generate: ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	go tool controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt: ## Run go fmt against code.
	go mod tidy
	go fmt ./...
	find . -type f -name '*.go' ! -path './zz_generated*' -a ! -exec grep -q '// Code generated by' {} \; -exec go tool gci write -s standard -s default -s "prefix(github.com/falcosecurity/falco-operator)" {} \;
	find . -type f -name '*.go' ! -path './zz_generated*' -a ! -exec grep -q '// Code generated by' {} \; -exec go tool addlicense -l apache -s -c "(C) The Falco Authors" {} \;
	find . -type f -name '*.go' ! -path './zz_generated*' -a ! -exec grep -q '// Code generated by' {} \; -exec $(SED_INPLACE) -E 's|// Copyright ([0-9]{4}) \(C\) The Falco Authors|// Copyright (C) \1 The Falco Authors|' {} +

.PHONY: vet
vet: ## Run go vet against code.
	go vet ./...

.PHONY: test
test: manifests generate fmt vet ## Run tests.
	KUBEBUILDER_ASSETS="$(shell go tool setup-envtest use $(ENVTEST_K8S_VERSION) -p path)" go test $$(go list ./... | grep -v /e2e) -coverprofile cover.out

.PHONY: test-e2e
test-e2e: manifests generate fmt vet ## Run the e2e tests. Expected an isolated environment using Kind.
	@command -v kind >/dev/null 2>&1 || { \
		echo "Kind is not installed. Please install Kind manually."; \
		exit 1; \
	}
	@kind get clusters | grep -q 'kind' || { \
		echo "No Kind cluster is running. Please start a Kind cluster before running the e2e tests."; \
		exit 1; \
	}
	go test ./test/e2e/ -v -ginkgo.v

.PHONY: lint
lint: ## Run golangci-lint linter
	go tool golangci-lint run --new-from-rev main

.PHONY: lint-fix
lint-fix: ## Run golangci-lint linter and perform fixes
	go tool golangci-lint run --fix

.PHONY: lint-config
lint-config: ## Verify golangci-lint linter configuration
	go tool golangci-lint config verify

.PHONY: update-kube-static-scheme-parser
update-kube-static-scheme-parser: ## Update the kube-static-structs parser
	hack/update-kube-static-scheme-parser.sh
##@ Build

.PHONY: build
build: manifests generate fmt vet ## Build manager binaries.
	go build -o bin/instance-operator ./cmd/instance
	go build -o bin/artifact-operator ./cmd/artifact

.PHONY: run
run: manifests generate fmt vet ## Run a controller from your host.
	go run ./cmd/instance

GOARCH ?= $(shell go env GOARCH)
.PHONY: docker-binaries
docker-binaries: ## Build Go binaries for Docker image.
	CGO_ENABLED=0 GOOS=linux GOARCH=$(GOARCH) go build -ldflags \
		"-s -w \
		-X '$(PROJECT)/internal/pkg/version.SemVersion=$(RELEASE)' \
		-X '$(PROJECT)/internal/pkg/version.GitCommit=$(COMMIT)' \
		-X '$(PROJECT)/internal/pkg/version.BuildDate=$(BUILD_DATE)' \
		-X '$(PROJECT)/internal/pkg/version.ArtifactOperatorImage=$(ARTIFACT_OPERATOR_IMAGE)'" \
		-o bin/linux/$(GOARCH)/manager ./cmd/$(OPERATOR)/main.go
	chmod 755 bin/linux/$(GOARCH)/manager

.PHONY: docker-build
docker-build: docker-binaries ## Build docker image with the manager.
	$(CONTAINER_TOOL) build \
		-t ${IMG} \
		-f build/Dockerfile .

.PHONY: docker-push
docker-push: ## Push docker image with the manager.
	$(CONTAINER_TOOL) push ${IMG}

# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry (i.e. if you do not set a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: ## Build and push docker image for the manager for cross-platform support
	$(MAKE) docker-binaries GOARCH=amd64
	$(MAKE) docker-binaries GOARCH=arm64
	- $(CONTAINER_TOOL) buildx create --name falco-operator-builder
	$(CONTAINER_TOOL) buildx use falco-operator-builder
	- $(CONTAINER_TOOL) buildx build \
		--push \
		--platform=$(PLATFORMS) \
		--tag ${IMG} \
		-f build/Dockerfile .
	- $(CONTAINER_TOOL) buildx rm falco-operator-builder

.PHONY: build-installer
build-installer: manifests generate ## Generate a consolidated YAML with CRDs and deployment via Helm.
	mkdir -p dist
	@img="$(IMG)"; \
	helm template falco-operator chart/falco-operator --namespace falco-operator --include-crds --set image.repository="$${img%:*}" --set-string image.tag="$${img##*:}" > dist/install.yaml

##@ Deployment

ifndef ignore-not-found
  ignore-not-found = false
endif

.PHONY: install
install: manifests ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	$(KUBECTL) apply --server-side=true -f chart/falco-operator/crds/

.PHONY: uninstall
uninstall: ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
	$(KUBECTL) delete --ignore-not-found=$(ignore-not-found) -f chart/falco-operator/crds/

.PHONY: deploy
deploy: manifests ## Deploy operator to the K8s cluster specified in ~/.kube/config via Helm.
	@img="$(IMG)"; \
	helm upgrade --install falco-operator chart/falco-operator --namespace falco-operator --create-namespace --set image.repository="$${img%:*}" --set-string image.tag="$${img##*:}"

.PHONY: undeploy
undeploy: ## Undeploy operator from the K8s cluster specified in ~/.kube/config via Helm.
	helm uninstall falco-operator --namespace falco-operator --ignore-not-found

##@ Dependencies

## Tool Binaries
KUBECTL ?= kubectl

## Tool Versions
#ENVTEST_K8S_VERSION is the version of Kubernetes to use for setting up ENVTEST binaries (i.e. 1.31)
ENVTEST_K8S_VERSION ?= $(shell go list -m -f "{{ .Version }}" k8s.io/api | awk -F'[v.]' '{printf "1.%d", $$3}')
