apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: rulesfile-inline
spec:
  priority: 50
  inlineRules: |
    - rule: Test Inline Rule Updated
      desc: Updated test rule for e2e reconciliation testing
      condition: evt.type = open
      output: "Updated rule triggered"
      priority: INFO
      enabled: false
