# This rule is not used by the project falco-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over instance.falcosecurity.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: falco-operator
    app.kubernetes.io/managed-by: kustomize
  name: falco-admin-role
rules:
- apiGroups:
  - instance.falcosecurity.dev
  resources:
  - falcos
  verbs:
  - '*'
- apiGroups:
  - instance.falcosecurity.dev
  resources:
  - falcos/status
  verbs:
  - get
