apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Plugin
metadata:
  labels:
    app.kubernetes.io/name: falco-operator
    app.kubernetes.io/managed-by: kustomize
  name: plugin-sample
spec:
  ociArtifact:
    image:
      repository: falcosecurity/plugins/plugin/container
      tag: main
    registry:
      name: ghcr.io
