apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  labels:
    app.kubernetes.io/name: falco-operator
    app.kubernetes.io/managed-by: kustomize
  name: rulesfile-sample
spec:
  ociArtifact:
    image:
      repository: falcosecurity/falco-rules
      tag: latest
    registry:
      name: ghcr.io
      auth:
        secretRef:
          secretName: my-pull-secret
