apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Falco
metadata:
  labels:
    app.kubernetes.io/managed-by: falco-operator
  name: falco-sample
spec: {}
  # type: DaemonSet
  # updateStrategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  # type: Deployment
  # replicas: 2
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 1
