apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  labels:
    app.kubernetes.io/managed-by: falco-operator
  name: component-sample
spec:
  component:
    type: metacollector
    version: "0.1.2"
  replicas: 1
  # podTemplateSpec: {}
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 1
