apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: rulesfile-oci
spec:
  description: Test Rulesfile with OCI artifact reference
  steps:
    - name: Create Falco instance
      try:
        - apply:
            file: 00-falco.yaml
        - assert:
            file: 01-assert-falco-ready.yaml
    - name: Wait for Falco pod to be ready
      try:
        - wait:
            apiVersion: v1
            kind: Pod
            selector: app.kubernetes.io/instance=falco-test
            timeout: 90s
            for:
              condition:
                name: Ready
                value: "true"
    - name: Create Rulesfile from OCI registry
      try:
        - apply:
            file: 02-rulesfile.yaml
    - name: Verify rules file exists in Falco pod
      try:
        - command:
            entrypoint: bash
            args:
              - ./verify.sh
            timeout: 120s
            env:
              - name: NAMESPACE
                value: ($namespace)
      catch:
        - command:
            entrypoint: bash
            args:
              - ../scripts/debug-artifact.sh
            timeout: 30s
            env:
              - name: NAMESPACE
                value: ($namespace)
