name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5.0.0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
