name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-e2e:
    name: tests-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          version: v0.31.0
          cluster_name: kind

      - name: Run e2e tests
        run: |
          go test ./test/e2e/ -v -ginkgo.v
