name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-e2e:
    name: tests-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Create kind cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
        with:
          version: v0.31.0
          kubectl_version: v1.36.4
          node_image: kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
          cluster_name: kind

      - name: Run e2e tests
        run: |
          go test ./test/e2e/ -v -ginkgo.v
