name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Setup envtest binaries
        run: |
          ENVTEST_K8S_VERSION=$(go list -m -f '{{ .Version }}' k8s.io/api \
            | awk -F'[v.]' '{printf "1.%d", $3}')
          KUBEBUILDER_ASSETS="$(go tool setup-envtest use "${ENVTEST_K8S_VERSION}" -p path)"
          echo "KUBEBUILDER_ASSETS=${KUBEBUILDER_ASSETS}" >> "$GITHUB_ENV"

      - name: Run tests
        run: |
          go test $(go list ./... | grep -v /e2e) -coverprofile cover.out
